# Generated by Django 5.0.6 on 2025-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-normal,1-trending'),
        ),
    ]
