# Generated by Django 5.0.6 on 2025-07-31 07:09

import django.db.models.aggregates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_updated_at_alter_category_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_line1',
            field=models.TextField(blank=True, max_length=django.db.models.aggregates.Max, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='address_line2',
            field=models.TextField(blank=True, max_length=django.db.models.aggregates.Max, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
