# Generated by Django 5.0.6 on 2025-08-01 06:34

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders_address_line1_orders_address_line2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shop.models.getFilename)),
                ('primary_color', models.CharField(default='#FF5733', max_length=7)),
                ('secondary_color', models.CharField(default='#00AACC', max_length=7)),
                ('font_family', models.CharField(default='Roboto', max_length=100)),
                ('dashboard_html', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
