# Generated by Django 5.0.6 on 2025-06-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
    ]
