# Generated by Django 5.0.6 on 2025-07-02 14:45

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.getFilename),
        ),
    ]
